### ISSUE TITLE
storm jar failed to find guava

### ISSUE THREAD

**Issue by jiamo** [P7h/StormWordCount#1]
Hi, using storm jar and I met this error:

Caused by: java.lang.ClassNotFoundException: com.google.common.base.Stopwatch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

I don't change pom.xml. Just rm the librarys  in .idea , and using storm-0.9.4's storm to submit. In storm-0.9.4  libs dir can't find guava lib.

**Comment by jiamo** [comment]
I think we can do somthing like this:

//import com.google.common.base.Stopwatch;
import org.apache.storm.guava.base.Stopwatch;
